//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeServiceUtility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailTemplateCollection {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplateCollection() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeServiceUtility.EmailTemplateCollection", typeof(EmailTemplateCollection).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&apos;color:#c00000; font: bold; font-family:Segoe UI Light; margin: 0 0 0 180px;&apos;&gt;Call to Action&lt;/p&gt;
        ///&lt;p&gt;Please follow the steps mentioned 
        ///   &lt;a href=&apos;https://microsoft.sharepoint.com/teams/Business_Operations_Global/COSMIC/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FBusiness%5FOperations%5FGlobal%2FCOSMIC%2FShared%20Documents%2FSupport%20Docs%2FAlert%20Action%20Plan&apos;&gt;in this document &lt;/a&gt; 
        ///   to troubleshoot and follow the escalation path as needed.
        ///&lt;/p&gt;.
        /// </summary>
        internal static string MailboxUpdateAlertCallToActionMsg {
            get {
                return ResourceManager.GetString("MailboxUpdateAlertCallToActionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are receiving this alert as there are pending emails to be delivered in Cosmic Production Application https://cosmic.crm.dynamics.com
        ///&lt;p&gt;Please review the table and take the actions outlined below&lt;/p&gt;.
        /// </summary>
        internal static string MailboxUpdateAlertErrorMessage {
            get {
                return ResourceManager.GetString("MailboxUpdateAlertErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p style=&apos;color:#c00000; font: bold; font-family:Segoe UI Light; margin: 0 0 0 180px;&apos;&gt;Escalation path&lt;/p&gt;
        ///&lt;p&gt;If you need assistance in solving this issue, please immediately reach out to CRMSrvOps@microsoft.com.&lt;/p&gt;
        ///&lt;p&gt;Please make sure to copy , dynarc@microsoft.com.&lt;/p&gt;.
        /// </summary>
        internal static string MailboxUpdateAlertEscalationPathMsg {
            get {
                return ResourceManager.GetString("MailboxUpdateAlertEscalationPathMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmic MailBox(es) Error.
        /// </summary>
        internal static string MailboxUpdateAlertTableHeading {
            get {
                return ResourceManager.GetString("MailboxUpdateAlertTableHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are receiving this report as there are multiple workflows failing in Cosmic Production Application https://cosmic.crm.dynamics.com
        ///&lt;p&gt;Please review the table&lt;/p&gt;.
        /// </summary>
        internal static string WorkFlowFailuresErrorMessage {
            get {
                return ResourceManager.GetString("WorkFlowFailuresErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Alert COSMIC.
        /// </summary>
        internal static string WorkFlowFailuresTableHeading {
            get {
                return ResourceManager.GetString("WorkFlowFailuresTableHeading", resourceCulture);
            }
        }
    }
}
